apiVersion: v1
kind: Service
metadata:
  name: seoul-fit-fe
  labels:
    app.kubernetes.io/name: seoul-fit-fe
    app.kubernetes.io/component: frontend
    app.kubernetes.io/part-of: seoul-fit
spec:
  selector:
    app.kubernetes.io/name: seoul-fit-fe
  ports:
    - name: http
      port: 3000
      targetPort: http
      protocol: TCP
