apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultAuth
metadata:
  name: seoul-fit-fe
  labels:
    app.kubernetes.io/name: seoul-fit-fe
    app.kubernetes.io/part-of: seoul-fit
spec:
  vaultConnectionRef: seoul-fit-fe-vault
  method: kubernetes
  mount: kubernetes
  kubernetes:
    role: PLACEHOLDER
    serviceAccount: seoul-fit-fe-vso
    tokenExpirationSeconds: 600
    audiences:
      - vault
